### PR TITLE
[#49] send pictures to firebase

### LINKED ISSUE #49: Send pictures to Firebase
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Send pictures to Firebase   | 1 | 3 |

This aims to recreate Instagram's basic image sharing feature. This only takes care of the "sharing" part, and does not cover retrieving the image form the database and displaying it properly.

------------------------------------------

## Task List

- [x] A submit button prompts the user for a single file
- [x] A thumbnail image properly appear
- [x] A text input for the caption properly appear
- [x] The "Share" button properly sends the picture, caption and user id to Firebase.
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* When the user is logged in, a button shall appear prompting for an image from the user's device.
* After selecting a file from the user's device, a small preview shall appear on the page which displays the image.
* After selecting a file from the user's device, a small preview shall appear on the page which displays the image, and the user shall be prompted for an optional caption.
* Upon clicking the "Share" button, the picture alongside the caption and user id shall be sent to Firebase.

------------------------------------------

## Related features/user stories

* [#8] User Story 1: Uploading Pictures
* [#47] User Account Login
* [#48] Integrate Firebase

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

### PR DESCRIPTION
**Pull request by tjosepo**
## Summary

This PR adds a 'New post' button. Once clicked, it opens up a dialog that prompts the user for an image and caption. Once the submit button is pressed, the image is sent to the Firebase storage, and the post information is sent to the Firestore database.

This PR used Material for styling.

## Related Issue

* Resolves #49 Send Pictures to Firebase

## Testing 

1. Checkout branch or go to https://shutterfeed-soen341.firebaseapp.com/
2. Follow the steps to submit an image.
3. Check on Firebase to see if the information properly appears.

### CODE REVIEW

**Comment by laurentlaurent** [comment]
@tommy-josepovic Damnnnnn. Nice.

Can you provide some documentation in `/docs` on how to use what you've done? Otherwise, seems good to me

**Review by laurent-lao — CHANGES_REQUESTED** [review]
@tommy-josepovic Damnnnnn. Nice.

Can you provide some documentation in /docs on how to use what you've done? Like if we want to create components that hook into it and stuff. Linking the guide you used (if any) can be enough. Otherwise, seems good to me

**Review by CamilBouzidi — CHANGES_REQUESTED** [review]
I agree with @laurentlaurent . We could use a little bit more explanation since some members on the team are not as familiar with Angular and Angular Materials, but the code itself is well-written and well-structured!

**Review by A-Robitaille — CHANGES_REQUESTED** [review]
I also agree, it could use a bit of documentation. Otherwise, looks good

**Review by laurent-lao — APPROVED** [review]

**Comment by laurent-lao** [comment]
Issues raised at #69 so we can approve this ASAP

**Pull request merged**
