### PR TITLE
Camil bouzidi wiki update april4

### PR DESCRIPTION
**Pull request by CamilBouzidi**
## Summary

This PR fleshes out how User Stories are connected to our backend and also adds the missing meeting minutes. 

## Related Issue

* Fixes/Resolves/Closes #xx Issue

## Testing 

1. Steps to test the PR

### CODE REVIEW

**Review by jmezaber — COMMENTED** [review]
@CamilBouzidi The document "March 20" and "March 24" both have the same content, while both being added to separate files in the "meeting minutes". Was the same content discussed on both days?

**Comment by CamilBouzidi** [comment]
Hi @jmezaber, thank you for pointing it out! I was editing the march 24th document and forgot to save it. I'll change that right now!

**Comment by CamilBouzidi** [comment]
Hello again @jmezaber,

The March 24th file has been updated properly. Please let me know if there is anything else!

**Review by jmezaber — APPROVED** [review]
Thank you for fixing it!

**Pull request merged**
